# Generated by Django 3.1.7 on 2021-03-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_language_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='code',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
