# Generated by Django 3.1.7 on 2021-03-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210305_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
